parameters: {}
environment: {}
packages:
    - name: caramelbeard
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: create-masked-email
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          webSecure: ''
          parameters: {}
          environment: {
              'FM_USERNAME': '',
              'FM_TOKEN': '',
              'DOMAIN': '',
          }
          annotations: {}
          limits: {
              'memory': 256,
              'timeout': 6000,
          }
